# Generated by Django 5.0 on 2023-12-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=2000)),
                ('Profilepicture', models.ImageField(upload_to='uploads/')),
                ('username', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=2000)),
                ('confirmpassword', models.CharField(max_length=2000)),
                ('address_line', models.CharField(max_length=2000)),
                ('address_city', models.CharField(max_length=2000)),
                ('address_state', models.CharField(max_length=2000)),
                ('address_pincode', models.CharField(max_length=2000)),
            ],
        ),
    ]
