# Generated by Django 5.0 on 2023-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Profilepicture',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='address_city',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='address_line',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='address_pincode',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='address_state',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='firstname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='register',
            name='lastname',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
