# Generated by Django 5.0 on 2023-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_register_profilepicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
